name: seattle_elite_towncar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  currency_text_input_formatter: ^2.1.10
  dio: ^5.3.2
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.10.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.0
  flutter_local_notifications: ^16.1.0
  flutter_map: ^5.0.0
  flutter_multi_formatter: ^2.11.7
  flutter_native_splash: ^2.3.1
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  form_builder_validators: ^9.0.0

  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  go_router: ^10.0.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  location_permissions: ^4.0.1
  retrofit: ^4.0.1
  sentry_flutter: ^7.10.1
  shared_preferences: ^2.2.2
  stream_transform: ^2.1.0
  url_launcher: ^6.1.14
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/root_main_image.png
    - assets/icons/

  fonts:
    - family: SansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#3052AA"
  image: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#3052AA"

  web: false
